### ISSUE TITLE
Topbar buttons stacked on window controls

### ISSUE THREAD

**Issue by ayush729p** [notion-enhancer/desktop#572] opened 2021-09-03 05:04 UTC
**describe the bug**
Topbar buttons (Share, Updates, Favorite, Overflow Context Menu) are getting stacked on window controls. It is also overlapping on the buttons which make it difficult to access.
Happened randomly to me, was working fine before. Just opened it one day to find it like this (Maybe yesterday or day before that). Updated enhancer about a week ago.

**expected behaviour**
Topbar buttons must be beside the windows control not on top of them. Like this (taken from an old screenshot):
![image](https://user-images.githubusercontent.com/71623044/131952025-5fceebec-b27d-435e-8de9-c1653a7c824a.png)

**screenshots**
Looks like this now:
![image](https://user-images.githubusercontent.com/71623044/131951490-598bb2f2-c7c5-44d5-91c8-c0ca2b53c695.png)

Enabling tabs does not face this issue:
![image](https://user-images.githubusercontent.com/71623044/131953021-c90f5bd9-1530-4786-a776-81aaa9835a78.png)

But I don't use tabs since it was buggy earlier, don't know the state of it now.

**platform**
Windows 10 21H1
Notion 2.0.16, Enhancer v0.10.2 with v2.0.13+ fix applied.

**troubleshooting done**
Reinstalled notion app, reinstalled notion enhancer (defaulting everything) - Problem still persists
Tried Notion-repackaged, but [window controls are bugged in that](https://github.com/notion-enhancer/notion-repackaged/issues/21) whose parent bug is #291 (is this the cause of this issue too?).

Tried disabling/enabling the integrated title bar from the enhancement section but to no avail :(

**Comment by jerryc127** [comment] 2021-09-04 05:32
![image](https://user-images.githubusercontent.com/16351105/132083760-97b26334-3fe9-4b22-87f2-cc636c4ab090.png)
i have a same problem

**Comment by siwuxei** [comment] 2021-09-04 07:27
![image](https://user-images.githubusercontent.com/50586809/132086581-29e2d679-7321-4f12-b97a-fe53fd9eee0c.png)
same

Duplicate of #

**Comment by sammusaev** [comment] 2021-09-04 12:07
![Notion_HOLUXnO2Mu](https://user-images.githubusercontent.com/68367753/132093856-b0c48881-95b7-4aab-89c9-8d9652a44233.png)
Same issue on a clean install

**Comment by hackettk** [comment] 2021-09-04 13:58
same !!!  please quick repair，thank！

**Comment by dragonwocky** [comment] 2021-09-04 14:11
a temporary fix is to add this to your custom inserts css:
css```
.notion-topbar-action-buttons {
    top: 17px !important;
    right: 109px !important;
}
```

**Comment by Nico-Mayer** [comment] 2021-09-06 13:00
> a temporary fix is to add this to your custom inserts css:
> 
> ```css
> .notion-topbar-action-buttons {
>     top: 17px !important;
>     right: 109px !important;
> }
> ```

Where do i find this css file?

**Comment by dragonwocky** [comment] 2021-09-06 13:19
@Nico-Mayer you create it yourself anywhere and add it to the enhancer with the custom inserts mod in the menu.

**Comment by Red-Verlin** [comment] 2021-09-08 12:37
> a temporary fix is to add this to your custom inserts css:
> 
> ```css
> .notion-topbar-action-buttons {
>     top: 17px !important;
>     right: 109px !important;
> }
> ```

Topbar buttons not hiding in Focus Mode. I know you mentioned adding the fix here in #571 but didn't see it. Just wondering if it's still in the works or if I somehow missed it.

**Comment by dragonwocky** [comment] 2021-09-08 12:51
@Red-Verlin you can see what needs changing [here](https://github.com/notion-enhancer/notion-repackaged/blob/main/patches/enhancer/focus-mode-titlebar-buttons.patch), it will be part of an update to notion-repackaged that will be released soon (just needs a bit more testing).

**Comment by dragonwocky** [comment] 2021-09-09 13:13
Try https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-3

**Comment by ayush729p** [comment] 2021-09-09 15:42
> Try https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-3

Uninstalled Notion + Enhancer and installed Repackaged once again. Can confirm it works!!!

Default Light Theme:
![image](https://user-images.githubusercontent.com/71623044/132717777-04aff055-f34a-450a-b7a3-c4a92a166927.png)

Material Ocean:
![image](https://user-images.githubusercontent.com/71623044/132717689-6aa59b28-eab2-4c9c-9039-989c635c5b8f.png)

and also works with tabs enabled ([the quick fix given above](https://github.com/notion-enhancer/notion-enhancer/issues/572#issuecomment-912980981) broke the tabs window controls a bit):
![image](https://user-images.githubusercontent.com/71623044/132718127-2da74572-c449-43e2-9364-b777f3e254e7.png)

**Closed** 2021-12-31 09:55 UTC
Labels: bug, awaiting release
