### ISSUE TITLE
Lags (More Info)

### ISSUE THREAD

**Issue by TvoozMagnificent** [notion-enhancer/desktop#735] opened 2022-02-22 09:33 UTC
1. How am I supposed to know how to reproduce this? Every time I open this specific notion file it lags hard. 
2. No, it doesn't lag for other smaller files, not because of pictures, code, anything like that. 
3. It seemingly is because of large files. How to prevent this? 
4. I think you can reproduce this by making a very large file and adding lots of addons. 
5. I have `fontchooser`, `tray`, `tabs`, `view scale`, `scroll to top`, `indentation lines`, `bypass preview`, `word counter`, and `truncated titles` on. 
6. Fontchooser info: <img width="359" alt="Screen Shot 2022-02-22 at 5 30 32 PM" src="https://user-images.githubusercontent.com/98521363/155103294-d61554bb-f1db-4211-8065-c51d645427f8.png">
7. Themes: `light+`, `neutral`
8. Individual themes or addons don't seem to cause the problems. Conflicts maybe? 

How should I solve this? 
My mac version: 
<img width="254" alt="Screen Shot 2022-02-22 at 5 32 52 PM" src="https://user-images.githubusercontent.com/98521363/155103753-b4ad523a-8504-41f7-8e0a-5702c32447a4.png">

Seriously I just can't use this!

**Comment by dragonwocky** [comment] 2022-02-22 09:58
I did some further testing a separate machine:
- some of the lag is caused by the theming system, this is unavoidable (see the bottom of https://notion-enhancer.github.io/documentation/concepts/)
- some of the lag is caused by the word counter extension - it could probably do with some optimisations

Your options are
a) disable your themes
OR b) disable the word counter
OP c) stick to smaller pages

closing this again because it's a support request, not a bug report. if you would like to open a bug report about the word counter lag, you can do so in https://github.com/notion-enhancer/repo/issues and you **must** fill in the provided template.

**Closed by dragonwocky** 2022-02-22 09:58 UTC
Labels: bug
