### ISSUE TITLE
Notion native grey background color in the title areas across all dark themes

### ISSUE THREAD

**Issue by serjanbiogenic** [notion-enhancer/desktop#704] opened 2022-01-06 01:09 UTC
**What is happening?**
All Notion dark themes do not override Notions' default grey color in specific areas, see screenshot

**What should be happening?**
should be cohesive with the theme color

**Screenshots (if applicable):**
https://drive.google.com/file/d/19uOoBAoQ3fLP9tTBgYCqBOnC9OiLlYiW/view?usp=sharing
https://drive.google.com/file/d/1A7mTAjx6OErEvfbvuIRRhmHd7xQ6YwVd/view?usp=sharing

**Operating system/browser name & version:**
Windows 10 21H2

**notion-enhancer and/or notion-repackaged version:**
0.11.0

**notion-enhancer configuration (enabled/disabled mods and their settings):**
any dark theme, like Neutral or Dark+

**Comment by dragonwocky** [comment] 2022-01-06 08:35
duplicate of https://github.com/notion-enhancer/repo/issues/37 and in the wrong location

please follow the [contributing guidelines](https://notion-enhancer.github.io/about/contributing/) or your bug reports / feature requests will be closed

**Closed by dragonwocky** 2022-01-06 08:35 UTC
Labels: bug
