### ISSUE TITLE
White Window Bug even after uninstall and reinstall

### ISSUE THREAD

**Issue by Michael-Adu** [notion-enhancer/desktop#298] opened 2020-12-01 11:59 UTC
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

The Bug:
The window is just white with no clickable things. Was able to uninstall the notion enhancer and Notion returned to normal. Upon reinstalling it, the window became white again.

Expected Behaviour:
It should not be so

Screenshots:
![image](https://user-images.githubusercontent.com/72309685/100737759-7f7a5280-33cc-11eb-9f36-c342a3a40c19.png)

Platform:
Windows 10

**Comment by joshdavies14** [comment] 2020-12-01 17:40
If this only happened today it's due to an updated Notion client. A fix is being worked on

**Comment by Zyjinn** [comment] 2020-12-01 22:54
> 
> 
> If this only happened today it's due to an updated Notion client. A fix is being worked on

Notion had an update today?

**Comment by lhecht** [comment] 2020-12-02 09:28
> If this only happened today it's due to an updated Notion client. A fix is being worked on

Thank you very much for this tool. I dont want to complain, but because this has happened now a second or third time with a notion update (having the same all white problem), maybe there is a way to cope with it in the future. For example it could be a possibility to add a temporary disable of notion-enhancer. So that I dont have deinstall and install it later again every time, when an update happens? Or am I too stupid and there is a fast way to disable notion-enhancer?

**Comment by dragonwocky** [comment] 2020-12-02 09:32
The enhancer integrates too deeply with the notion app for there to be an on/off switch, and there's no way to predict what changes a notion update will make. The simple fact of the matter is: the enhancer is not separate to notion, it is a hack that taps into parts of notion, and updates that include codebase changes will always break it.

**Comment by lhecht** [comment] 2020-12-02 11:30
> The enhancer integrates too deeply with the notion app for there to be an on/off switch, and there's no way to predict what changes a notion update will make. The simple fact of the matter is: the enhancer is not separate to notion, it is a hack that taps into parts of notion, and updates that include codebase changes will always break it.

Thank you for your quick reply. Ok, I understand the issue. When uninstalling I recognized, that it keeps a config file, so hopefully that is almost like an "on/off"-switch :) Keep up the good work.

**Comment by Kirakeru** [comment] 2020-12-02 14:54
Have a look at this simple fix. **Insert this code `enableRemoteModule: true` after `mods/core/createWindow.js` line 51 and `mods/core/tray.js` line 141**, relaunch Notion and everything works again. The fixed `createWindow.js` and `tray.js` should seem like this:
```JavaScript
// many lines of code
        webPreferences: {
          // some code
          session: electron.session.fromPartition('persist:notion'),
          enableRemoteModule: true, // <- add this line
        },
// many lines of code
```
I'll create a pull request for this fix in a couple of hours. Besides, you may have to **disable the core extension "tab"** after applying the changes, because this extension makes Notion unable to load its webview. This problem seems to be also caused by the Notion update, and I haven't found any clue for this yet, so any help is welcomed.

**Comment by denarkk** [comment] 2020-12-02 20:02
Great! It worked 😎

**Comment by QuentinHsu** [comment] 2020-12-03 03:30
I am also experiencing this problem with notion setup 2.0.11

**Comment by eexxyyq** [comment] 2020-12-03 08:32
You are trying to override window value in createWindow.js on line 75, however "window" variable is constant, after I cloned your repository I changed "const window" (line 43) to "let window". After running the preinstall script, everything worked for me on version notion 2.0.11

**Comment by dragonwocky** [comment] 2020-12-03 08:35
@eexxyyq thanks, i missed that, but that isn't the cause of this issue. the variable isn't reassigned until window close, while this bug is caused when the window fails to even open.

**Comment by eexxyyq** [comment] 2020-12-03 08:38
@dragonwocky ok, now i have another issue: combination Alt+E opening enhancer settings and windows explorer :D 
Everything still work for 2.0.11

**Comment by dnswd** [comment] 2020-12-03 14:31
@eexxyyq the issue is already posted on #306 and fixed in af2af96 and now awaiting for release

**Comment by OrelBenny** [comment] 2020-12-04 07:04
New here.. Is there a fix? Do I need to type something somewhere or just reinstall the enhancer?

**Comment by dragonwocky** [comment] 2020-12-04 07:38
@OrelBenny when the fix is released (in a few hours), just reinstall the enhancer and things will start working.

**Closed** 2021-12-31 09:55 UTC
Labels: bug, awaiting release
