### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by airsimonhan** [notion-enhancer/desktop#333] opened 2020-12-07 23:31 UTC
**describe the bug**
memory leak

**expected behaviour**
The new version is prone to memory leaks. I have 48GB

**screenshots**
![微信截图_20201208072529](https://user-images.githubusercontent.com/15105562/101417765-48092a00-3927-11eb-9e28-bd7328f9e84c.png)

**platform**
windows 10

**Comment by dragonwocky** [comment] 2020-12-08 00:09
@airsimonhan which extensions do you have enabled?

**Comment by airsimonhan** [comment] 2020-12-08 01:06
> @airsimonhan which extensions do you have enabled?

outliner

**Comment by dragonwocky** [comment] 2020-12-08 01:13
@airsimonhan only outliner? nothing else at all?
which options on the core extensions are enabled?

**Comment by airsimonhan** [comment] 2020-12-08 01:21
> @airsimonhan only outliner? nothing else at all?
> which options on the core extensions are enabled?

sorry for not being clear, notion works well before I enable the outliner. Besides, I have also enabled the follows:
- notion-enhancer core
- tabs
- tweaks
- bypass preview
- calendar scroll
- code line numbers
- dracula
- indentation lines
- panel sites
- side panel
- topbar icons

**Comment by airsimonhan** [comment] 2020-12-08 06:37
![image](https://user-images.githubusercontent.com/15105562/101448890-c6cf8880-3962-11eb-9e4e-fc8b5fcc9764.png)
appear again.

**Comment by CloudHill** [comment] 2020-12-08 07:25
@airsimonhan does this happen on all pages? and does it go back to normal if you disable the outliner?

**Comment by jerryc127** [comment] 2020-12-08 09:12
![image](https://user-images.githubusercontent.com/16351105/101463509-782ce900-3978-11eb-8081-9563523532f5.png)
i had close the notion
it is cause by notion or ?

**Comment by CloudHill** [comment] 2020-12-08 09:49
@jerryc127 can you elaborate? what's caused by notion?

**Comment by noelleclement** [comment] 2020-12-08 14:21
I'm not sure if related, but when I enable the side-bar and outliner features, the Windows app becomes incredibly slow (read: several seconds after typing, the characters appear). When I disabled them, it worked at (AFAIK) regular speed again.

**Comment by CloudHill** [comment] 2020-12-08 15:35
@noelleclement does the same happen if you disable the outliner, but enable panel sites? if you haven't set it up yet, you can go to #313 and use the example code to test it.

**Comment by noelleclement** [comment] 2020-12-10 08:25
@CloudHill Do you still need me to test the above, or is that addressed in the commit?

**Comment by CloudHill** [comment] 2020-12-10 08:28
@noelleclement yeah, i don't have the same performance issues, so i don't know for sure if the commit actually fixed anything, or if the outliner is the one causing the issue in the first place.

**Comment by noelleclement** [comment] 2020-12-10 09:16
@CloudHill So there's definitely a difference between solely having enabled side-panel & the combo side-panel+outliner. So by my observations the issue is with the outliner add-on. 
Didn't try it with your test code though, but hope this helps.

**Comment by CloudHill** [comment] 2020-12-10 09:34
@noelleclement did you have the **panel sites** mod enabled though? Because currently there are only two mods that uses the side panel extension: the outliner and panel sites. If neither is on, the side panel mod **doesn't actually do anything**. Just wanna make sure that the side panel isn't the one causing the issue.

**Comment by noelleclement** [comment] 2020-12-10 09:55
@CloudHill Aaah, sorry, misread that. Yep, tested it now with panel sites (without outliner) with the suggested example file, and the same issues seem to occur. The document stays responsive to mouse-moves, but actually clicking somewhere to start typing takes ages to trigger the 'typ-mode' and typing itself is very slow as described above. 
Hope that makes sense, I don't commonly code web / front-end.

**Comment by J-MR-T** [comment] 2021-01-25 15:36
For your information: I don't have the outliner enabled, but still get the memory leak (the maximum I have observed until now is 10.5/16 GB taken up by notion).
I have got:

- tweaks (integrated scrollbars, thicker bold text, scroll database toolbars)
- bypass preview
- dracula theme
- indentation lines (style soft, enabled for all lists)
- truncated table titles (I have enabled this one after the memory leak started appearing so its most probably not the cause)

In the core I have enabled:
- auto-resolve theme conflicts
- hide app on open
- close window to the tray
- integrated titlebar

Im on Windows 10

**Comment by NicKarlovich** [comment] 2021-02-03 03:02
I also had the same issue, twice now Notion(running this enhancer) has racked up 10GB of RAM before I killed it via task manager (using Windows 10).  These are all the things I have enabled:

core(hide app on open, auto-maximize windows, close window to tray, integrated titlebar)
tabs
tweaks(integrated scrollbars, scroll database toolbars)
bypass preview
code line numbers
dracula
side panel

**Comment by vysmaty** [comment] 2021-02-05 14:34
> I also had the same issue, twice now Notion(running this enhancer) has racked up 10GB of RAM before I killed it via task manager (using Windows 10). These are all the things I have enabled:
> 
> core(hide app on open, auto-maximize windows, close window to tray, integrated titlebar)
> tabs
> tweaks(integrated scrollbars, scroll database toolbars)
> bypass preview
> code line numbers
> dracula
> side panel

I run into this brutal leak (32 GB+ssd drive) multiple times. 

Intersection:
core(close window to tray, integrated titlebar)
tabs
tweaks(integrated scrollbars, scroll database toolbars)
**side panel** (personal suspect)

**Comment by consistentelephant70** [comment] 2021-02-20 22:58
The same issue here. It happens when I'm not using Notion at all (closed by "quit" button on toolbar), usually at night (London time). Could it be an update or something?

I don't use outliner nor side panel, so those two shouldn't cause the problem. 

Here's what I do use: 
core (auto-maximise, close to tray, integrated toolbar)
tweaks (integrated scrollbars, snappy transitions, thicker bold texts, scroll database toolbars)
topbar icons

**Comment by x-researcher** [comment] 2021-02-21 07:05
Same Issue.

Just close window to the tray and keep run in the background.  

> The same issue here. It happens when I'm not using Notion at all (closed by "quit" button on toolbar), usually at night (London time). Could it be an update or something?
> 
> I don't use outliner nor side panel, so those two shouldn't cause the problem.
> 
> Here's what I do use:
> core (auto-maximise, close to tray, integrated toolbar)
> tweaks (integrated scrollbars, snappy transitions, thicker bold texts, scroll database toolbars)
> topbar icons

Same to you.

**Comment by x-researcher** [comment] 2021-02-21 07:05
> The same issue here. It happens when I'm not using Notion at all (closed by "quit" button on toolbar), usually at night (London time). Could it be an update or something?
> 
> I don't use outliner nor side panel, so those two shouldn't cause the problem.
> 
> Here's what I do use:
> core (auto-maximise, close to tray, integrated toolbar)
> tweaks (integrated scrollbars, snappy transitions, thicker bold texts, scroll database toolbars)
> topbar icons

Same to you.

**Comment by vysmaty** [comment] 2021-02-21 15:37
> ....
> I run into this brutal leak (32 GB+ssd drive) multiple times.
> 
> Intersection:
> core(close window to tray, integrated titlebar)
> tabs
> tweaks(integrated scrollbars, scroll database toolbars)

Again:
Today without outliner, side panel...

> Intersection:
> core(close window to tray, integrated titlebar)
> tabs
> tweaks(integrated scrollbars, scroll database toolbars)

So for next time i turn off "close window to tray". I hate this bug so much! The torment of my SSD. :/

**Comment by J-MR-T** [comment] 2021-02-21 21:15
I can only assume that its either tabs or close to tray itself, with those disabled it does not occur anymore

**Comment by Mara-Li** [comment] 2021-02-24 18:40
I will add my case here too. Memory Leak here... 
![image](https://user-images.githubusercontent.com/30244939/109048083-f034c080-76d6-11eb-9a48-54d33f5417fc.png)
Yup.

And I DON'T HAVE Side panel/tab.

My plugins : (using dev branch)
> Core ; Autoresolve theme + integrated 
> Tweaks :  Snappy transition + Thicker bold text + Integrated  scrollbars + Hide help button + Scroll database toolbar
> Bypass preview
> Code line number
> Collapside headers
> Custom insert : Some CSS things
> Emoji set : Twitter
> Foot chooser 
> Global linking blocks
> Nord theme
> Simpler database
> Word counter

**Closed** 2021-12-31 09:55 UTC
Labels: bug, awaiting release
