### ISSUE TITLE
Notion doesn't open after npm install notion-enhancer

### ISSUE THREAD

**Issue by ofirporat** [notion-enhancer/desktop#808] opened 2023-08-09 08:22 UTC
**What is happening?**
Notion does not open after installing notion-enhancer through npm

**What should be happening?**
Notion opens.

**Screenshots (if applicable):**
![image](https://github.com/notion-enhancer/notion-enhancer/assets/41275113/55b33c35-2580-409b-ac5c-0e6c44eba38f)

**Operating system/browser name & version:**
Windows

**notion-enhancer and/or notion-repackaged version:**
Latest one on npm

**notion-enhancer configuration (enabled/disabled mods and their settings):**
idk..

**Comment by dragonwocky** [comment] 2023-08-09 10:10
The current release of the notion-enhancer isn't compatible with the latest release of the Notion app yet. If you'd like to use the notion-enhancer, you'll need to either use the browser extension or download and install the notion-repackaged version that comes with the notion-enhancer pre-included in the Notion app.

(duplicate of https://github.com/notion-enhancer/notion-enhancer/issues/684)

**Closed as completed by dragonwocky** 2023-08-09 10:10 UTC
Labels: bug, duplicate
